/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * Customer.java
 *
 * Created on May 27, 2012, 1:15:52 PM
 */

/**
 *
 * @author mahesh
 */
public class newCustomerInsert extends javax.swing.JFrame {

    /** Creates new form Customer */
    public newCustomerInsert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Customer Data");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Customer No. :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Customer name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Date :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("Customer Address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setForeground(new java.awt.Color(0, 102, 51));
        jLabel6.setText("Customer Phoneno. :");

        jTextField2.setForeground(new java.awt.Color(255, 204, 0));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.setForeground(new java.awt.Color(255, 204, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setForeground(new java.awt.Color(255, 204, 0));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setForeground(new java.awt.Color(102, 102, 0));
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton2.setForeground(new java.awt.Color(102, 102, 0));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setForeground(new java.awt.Color(102, 102, 0));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jComboBox1.setForeground(new java.awt.Color(255, 204, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jComboBox2.setForeground(new java.awt.Color(255, 204, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jComboBox3.setForeground(new java.awt.Color(255, 204, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2012", "2013", "2014", "2015" }));

        jTextField1.setForeground(new java.awt.Color(255, 204, 0));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/srg.JPG"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEéá©¨E]lu^Ô¦šê=¬ònÁ´#.='©?{¥¥ÔÉioÊ)‘—sÈ’ÊGÊ2Ã'M|m~£zÜêm9s'»ÿ 3Mn¶¨VÉßü@óÔãˆõ5~Âİ‘\¶=IÏLxöşuàC¦åe}N:µ\®_Ä¢8—``Ø8?x‘õ>¿Î®N“ŞEk´©g4D´¥†åtÊç-ÄSq³Z\ó*bUìŞ¬’K¸"·X–Dc¨wL;$ù¿/ğ«¨â[È-dd‘‰Ï2’	Ç<úƒŞ±tåßs¢…dŞŒ´<RHxá²Œ~çÉ<cµVY<ÉU¤ ;8öo¡äW+‡4´=X´àŸ[4Ïf³Hak™€"G@ï´d¹Ür§½yMş¹^Nnqñ‰Do(&1.î@8;}ëÛËğÒi%¹äâ+¸Õ·VÌ½/QÖ..Ò.VX&l:•Õ˜ıèÆs¡ï[ºı¤úŠå”Ü[å$“~‡-œu'oC‘ıêúÇ—rP‹±ÕGTô»dšwˆ¿´^2"û¢L¨YK³Œü¹,N°®Å.–ÜµÄÂiÃ2‰rì{dÃ_3¢ äÖ«ş	³„»[ï$+ñ\^‰É"ìµe]¬„Ä·PW‘ÓÒ±REŞÌ‘å‰ùÈç$dõñ×ó®\%.yÇN¦5'dû¢ÜÖÎ$`”3ƒÁN2JâµÖøEwrò‰ F?2¹ÈV‘ƒ¾¢¾§‡pO±áb¤å»ßşÍêvVïeû€äÊÊÃ!XÃ£#'#ƒ^E¬ÚÊ$9ØJH(G'#©ÎkÏÇIAµk#£/V’v½úœN¤ÑıPAº7òG–Àõ‘ˆÜAÁèH9ëÉ¯ŠÖâæîE*õ„†ç ‚;ûú{ÖX
×œcsê)MF	½:ˆ-#Kw†ERï´ÆÇq*}BƒóqøÖ½½£ÊR6ô_™¸ç<}îÿ …}MJéRßS²“ZêuQY<ÙæïÚÙàí!zg'¯¯¥xwÆ]fÓEµ– ’Ë-ÕD‚b7†sàşµòøºîM÷915‹]O‚o¶ÌîÅCîÏœÇ““œrA,?
‘l‰Š/-–ê<d¯p3È'=FVWz_úıO
¬ÜåÊüÉ®¬|ˆQøÁí×êG¯•3¤¬hV#¢ñÇı;×r¨ô÷´hÃÙ«-Ş¿×ùƒY«Æ$•ˆw(üÄ×îñÉ={Õ”14±®ÖmÈ2AF2yŒûÿ eíwó5Q²”b¬Í¨#‰ÓÊC·nNòp3ŒŒõ•</wƒr‹åC+Uáœ…,O'×&’œ›Ošé›(+Ş×eÈaDB±1PW¡Œô8±ùzTâ3qùä÷' §óçŞºKŒ.íËf:5ŠEÜêC#¼`ç=GQøâ™/™,Ë	ÎHc÷@¹  H¬åù´ßş	J–©ßb×›%¹¨-¿ ğO®^rjä8XIRC§®sÔçœòGãïXê¤ã-Bµ¬­»ş¿¯™ÙÂ4ğİO·Œœyÿ 
|;Úe,ÛÇ
I$äã‘óÍiKíYíşlæ”\]£­Ë\\Äª9'äç¯·5KÍµË»r¥X(n¼7 ¿—¿*¥T®·fôã»kD_hPƒ&Kq“œ{à“ÿ ×5™=«K÷ò1Ïaß9Î}ûŠªÛ~¥V‚jıæq×Ñˆ¼É	Á@É'óîO­sWV¡ò‡#q òCùëØã¹¯f“¼w¹æÔƒÖæz/Ù*–dÆ71,O8lúëNŞIUÎwnFAéÇ¥T­¼·0Tæ›oRXfòX¤œs…ç’zóüıElGµábsó{ò{`ıî3“[Ğºi?‰Pšm_C£Òo¤öÒÆ4/CåÕ”ã äã<ÿ œWÛuaçY}œ9†o+Ì*§rü£ N~f'?ZœdbéÊLú,µû×OV}±á­RD‚ÒÚà,vi3Î	Aç)dÆCO 6>¾µì{J&bxRXå9Ã)Á	ûÙ6}«ã1qnRw½ÏÑ°?uõ¹ë>YfxÕZÕ¶’Û³œwÉÅ{—‡æïu¸ß*BÉØ§ _çÏ­yÒ…££¼Ÿõæ{”gÌ×ó§áé´È	®-Ö]·w·—» |Ã=¿‡éë^Ù¤Ä­IB,Š@ÚxòÛ®ïlq’?•g4ç$şÏü9íBQQÕïoÀï<Ëk[X,ìb…c\ÜJ˜ßs3gtÉçv{ÿ *Ä×7-¿ú4"Òªub0y8èr;÷5Œâïï­EÌš–¥Èd‘LJÀC–bI&MÊxn½÷'µf*Y™¥/å’W’Y–vc–ryÉÏ9úÓŒ{/u›{[¦¶f°mcy_4j@%À<^¤‚q\~¨X’ Ü„İ€8^¸•·³ºº‰ÍR£OG{u{"[}¢ôD½2«rîSËfÇ*£<©ù²GzñmK"§»ˆC#>Ø•\HYÉÎTî^>oéS6’{Øòñ•9¡#âÚÃ1k:'öT¶æší5m‰G`™kpB»9Á+Èëõ¯ÈÃW¶zÖ¨Ñív*Lr@Ã$Œßç¾?}†I§N¥œ­cñ¾/ÂÔ‹uT[‹2tï
]\İÆ%.†Á8
§yè5õ_Á…š›ë¯£MrÚ„ °…p¡Q„¦WÈUÚNóŠı	Ä”p¶æ—âˆÃdõqÚ(Üúöÿ LÕ¬Ş>éã•$f8Óbàú¾µ¤»»»†wcDLIæV'#8<Œgú†OŒ†?
ªÇU8Üùlÿ %©—Ê>Ñi3JöÑ¬,äÛÎd?( ä†8 \Ÿç_üh×§†âòöG,k»o «“¹NÓŒ_—w±¯ŸÏ`âä—Ú<<%6§'ı~E¯ØÇÁ“k¿å¼¸ƒÍHšŞÖ(J–I&ºuBÈx¸dü¥^Ÿ<?m¢ŞøgNv×SÙéöÖñÏ:e O,0¯Ü-¹ïÛÖ¾jÃDößúş·>Ã
­M&µHû¿HˆÂÿ éÅbO,íòÈ)»Ÿw€8íí\î©v²^I	Â!!f«rs‘Ô’1õ®*Ó¼½5ùoşGUST¸³±u¸jí%çsµUÉ<{ç5Şxm¬¯ÍŒÒÜÈ–ì »Ä	É<*ö;sÇOçXºª×Z°wi÷=®ÇL	åŒºÆƒ
NG‘×ÔŸç]D!c4Ÿ.ÄO ò76NO¾1ÔÔ7)Ét·üe5^ÂOrÆD•”´„¸`’£ c×¦xÏ­bëWæææ,qCl"t¸‘#]êƒ$áöî\œgÖ¹ñ
ñmî¿¯ÔJJpnÛŸ‚ßğVïTğ¦°–-;YOpm.#ü»Hşó¹ä.å%2O­7¿³¦¬±x¶â±å×"Ÿ™vîp8 ß|†:‹““kUşg³“ÔåÅÑ³ŞKó_æ~¦xY­ÒO(ƒäÅ$¿<Ÿ1+‚P¨ç§ŸJûá„K©ÀÜÀ¬Ò,€I2ÄË#äQ»·ääüëâ³
jMè¤Jdræ£MÚ÷G×±„ˆ®¼¡çÙ´pÆÈp0~õQŒõÆM{N›n·‘¤Š7:üç#æ’}šøŒm_~]®ZF7gFúpò£©—pŞ¥†
	g,=1ßÚ¤m8q"ò9ÚŞíÉãõàb çn¤óGvìÍÑ„AP˜¤0Ìc(ÿ xtÜ¤ç©¨¬´HšàËœnc“´d`N¼}kÏW¿TÖÖ\×lÑºğü±H—X·u'ıâç’Jœ:ú{Öeö˜ïålbeætÿ wÜ“Z¨.fÖ­:­¦·G¨¢­¹¸`Åº†^Yvñß¯ó¯—¼mu¨Kkª[µìVt™ÉÚ¢DÜF\ƒóúŸZÒ•å?2©Ú£¾Éÿ Á<[M¾óî…¥ÂÛK4§ÉŠh£]Ì d’M ¿æ¾…ğGØµOº\Èˆ^Â‘Ç–mî«‘Nzš0ßâÿ †)&§£øO¥ôpqa¸yQV÷Œ‰ğ°… “øš÷ÍnŒÃ$bÛí0¤rÄS%6°ÄˆyÚN:çÖ”>8ÚWÿ ‡G.*M§Ìõ=8™aŒìıÒF¨XœüÀz·ZÆ¾Ó-¤µ¸º¶ß+……Ôœ°|äğ{ı=kºRJŸ‘ãŞÓºwğÇ#{d,%‰%È³uRKFs÷³šò­fÕÙ­ËnVŞr!_ö¹Ç½yU]K¾‡«…ôos6dÚíœn‘·ê	ü?É«6º•ÌMû…)}÷—pİ–#'Î}ë	Ô|Ûéÿ ïª”¡Í²ğÿ æzx†8™Ïş©œnÛæ<õûÄçükŞ¼0Ëk4·
 4ö‹k‚20\Hî½y<ŒZ÷òÉ)ÅßsåsË™ËìêzfŸw¡“ÈAIÈ==ëpÜFÑ…ã uÈîq×¸¯§ö*tÕµ>fª½Kõÿ †äÂ9ÏcÈ?—9¨¼¤iS99ÚO÷³Ôç'…yµ°ÖmõrK{¡óZei;cĞäc·_cĞÓ’È|­{ä<=»äŒ½ıkÑjIÚæÊJI732kFV–,'9ìxÏS8ÏÏ_Z„°P§s(`K3‚Iã9ëõ«ŒœUº•MÚVóş¿3‹¿ÂüÆ6g*TdsÎAfÉàwüq:›Ÿõr|ä,H*O]ÙÉ'‘Î}=jdœ“rÜö°®í;Zçz»ò¥ Áf*=NzóµæúÕË€Ã
c,FîrHã×·_OzçVIÛt}_?éIâémøˆî$†'ïDÆFy&¼›^º­m	AöXâ—{É†˜±Rá3ü@1ïéë]4iŞß×õ±ër¯gª¹ó?fwßÚLêÓ[ı™í‡Ìw" Îy9Üw
ù¿Ur×(e\pq‚~R}‰î{ŸJ÷ğÖJËSÀÌSå¿FV*°Ù‘
·›1dp¤ÚÃÎCgß±ª~éš—Ä-µ)íµ;„²I&æ;[«Œ…•‘MáˆÃsÚ»c^\ê1Z3à3%ñu?qş~ÈÚíÿ ´­ïbÔ4Ë™®Ví%-ip,â¸Å†à;{W£xSÁv{ok™î-¦i ‘ÇßÚßÂ˜ä+êòÌµå”Öçæ9¶.Tç8ÅŞÇ×ÚdÎš}²³»‰"Bşk´€sÀ<ñç\¿‹,b¿km Hƒ´¦úO™°CÎ~VÎO¾ß†…$’V>N­IÖ•Ü®y^†e¾’d u¸xÑÉÁÄÄ9Æşuì:=òÈÆÎL´0©Ì‰ó3(ts•İRŒ5Z™­%mµ<ßÅV÷W\=gI7"ÀøRN$ıáÇ¸ë?x‡F¸q©ÛEöhí½µ¯”¥£e,ûğY}¹ôõ¥Fjí5f)Jò“z?ó±Ûhú¥Ş¢Ö÷>i¹”í™v®íÄ„d6ãÖ¹/ß›Â^Ö'–â'³„iA¼Ç áçpàJ¬Lãfû¦s‚î×æ~&jw—Ş(¾ÔusD¸ÕÛP±y_F²1¤’p[ÿ ×^ƒ¢ÙEp"¸Ôc™³+!Î×o¼pç–ç¯­~cÖsªÒî~ïÃcCM=Ùéº]”åE¸E`Hàü›AÉÕêv6Šc³V%’;e7øg§n 'Ÿe¯—MóK›âş¿[Ÿ{	9GG£:5k´¿Ä#$Û}¨JùòÊ@Nrr_j¥©êK$2Áwqk9XDŒ±³‘ÊNX“š£ZV•ù´JçËõë‹[k»V(îb{;Ù‹üŞ[Œ ‚NöÈäâükäŸ\[A}¥İ¬·™ŠZÜ‰ƒ’ÒJÇqù¡5Œ¡.iIjtóÅ-Œú[Ãïn³Ã}cˆm™Rc'Ìñ™†Üú`šîââV!âà”ŞH
Üu>™'Ÿğ¬*?‡±1IÉ]_×æ_û+ZÀgº&GP¬$HÈGPÊ¹=GOzÍº-yqö¬’²*)N›…$ƒßàúŸZç”ä§µâÎ¨½$›µÍ+IçşÊ´Œ+C“b8å™rx,~§Ö ·ºV‰æŒ¸IL±2IÁ$hØóØœqü©Â£rihg»³êc^î%Qå0 cï¸'Ğc<s××Ò©¢yílíÎ@é•ç*C`ô$äÏb}ky.xßúóÆßÍ³I,a‚¶L¥ÇY	;ˆéÁ98úzW!"$(R&f‰İ›’OÌçœsÏJçöM½îˆ©~Vö’9­ULÌÈ‰‹’ q××¯ø×&ˆ·eQ&öó¡W.Ä·]£#ƒíZF<–ºÒ'äÚmêdj2Ei³É‚“.OÚ‘rÊùpã+´õçŞ¹=FIÒßÌRÛ.náR°bTçs0ìªs×ÓÒµ”ÓûšBM¹s–ñ³²É'˜Òr^LàèÇ×ŸÏÖªÜO,X0H»‡3ız½É¬÷vN÷2­¯ÈÅ–ñL¡[r*>	äoÈŒŸÒ£EŠêò7¼ÈóÂ9k70àã‘ë]4 Ö½>ım«,êò²Û=±ºxcŞ…ÌhÊòÇò¹aúô¯ñ“[ï&k©È…œyìy.
îA“¤³£z×LåOWr%9)ZÖ<sÂ÷¥„·i!RHÜëoÒg“‚yl_zûSÀ–Ç\µšíïV-ï¤è¯e]ÄÛÈ
¿.pE|½Y5‹U#¥ŸêuK¨á§éuV€şñ¢Ùés´’½›M%¼NĞÛfC²@ûOÌI9-é_Sx7ÁMåõÜ¤ŞM"Lğ†İn`#;K69Ç¸ô¯İ8R›ÅPÃÕ}?ËüÏæ8Í'Wˆ¡Ïû´ßş”Êš¥´w×w¶“B†%¼8ã'1ùi!ÇÔcåëØzÓ£ÒÌ0‹q±cÚ€¨eU ~Gó¯ÙèG÷j)ôÿ #ò‘r©ñ_úÿ ‡<‡â|qÛéÓNÓ£uYd…Ü.%rQxÎJ¼ÿ Zü/ı¦çû.»­[Ì7ÜÛJo­€F©tã ;qşMy˜úw„¯Ôõ0Òäµö_æ|<Ş#CH™fEcŒ?9<ûş&¹­CZšk ±ï‰6‚ Î	ÿ x“éµò•h®ví©ô4«iİú”?´æEhÙ¾Båºg–~¼‘Àîk)®o	-İºVÉ'¼ó“ìzûÖjšiµf[©~š–EÔëò—ûÙİƒõ8ïŒZkÈ‘¹‘IyeîNnùÏz¹R÷uêc)¥)]s1‘_Ëp¥÷lç¯9Á#±Çä}ê$–(æ,¼–lå‡ñdß©9«t’W}Dª.dš³f´¯4ˆœ8=O<ñŸÎ¦4Lw“÷@GÕ·ñ‡fù”•Ş‘ßñ7‚N2êïşb½ =»¼ÉŞÁˆ9bAöÉ<ÿ “YŞË$Œ!ÆP ÙÇßà}8õ­¨Á½úœ)¿i£³#†æHVHóŸ8n!O|àóßÖ¨]9f1F»!,0IäGU'ñ5³£¹
œ•’•ï¿õ÷R	¼ÀÉ `K{}ş”Û³-Â&b2’$RzòprqÉäçw¥gìÚ~ô~eÑ§vî¹uş¿B˜Å…e<<z{àƒÎ=k [´„”óX»»É<Œœö5çbco3¶òJI½,E#ÄnŠü»È¡F0Ç9898 gó¨¥¶>dˆñü¹Éäú“Ÿ~æ¼yÉ¿8¡Ó§)I>¨Ğ²µ2¼hÙxLub	 ç¼ŸZú'ÂÚ|¶ğ9Êmª ¶íÄQŒw—JùüÃá>Ë‡á%Z7wZ~gÓ¾
ó®Ëí´Ë L{ ÇÌÀç°Ï#ŸÆ½ÎÂF{¦¶M™‹*€EHànşø×Åâ¤ï&İÚ?sÊ`•()k¡èV3Ö!Ô¯”©Ê€¹ ƒıqJêtå’ÚFƒøR«qÎ~‡¥y5)Ë;ÿ _×ê}]+5k…µ¬€gØçœà÷ãô®‰`O9¾mÀm#9Ş'œ’0}éU‚³Ğô°ÿ gúê/Ùô©eİö•XÀ(-Ìg=ƒ.GÉŒò=jíİ¡1€Šv²î€ò`§ ãÔv>•äÎ‹œ›å½VR9ç‘à‰£Çvå}¤ğ§†£Ûµq—q24gŸ3o\°º=?:Ö”m¥Øå.fÎ/Ä+“>ä7ƒœpÃ³g½­y·um",“KGş,‘“ƒ‚:Œg½wBïÒ+SZÒmlpûå¾r§€À€yÈ?‰9­µ…¢€+».8;ºH>¸¯3®äÚİŸÕ>Óÿ „ŠµÚ·µd–ß½`¬wBäøŸÖ´Ïš€„Á
@Û€_ÔÜuêÕáÔ†Ï{ÿ ™ı²·õıl_“|°ÂÁÊ2…fRxä:ıj½ÍÂ«÷‡äsÎAÉ5*Nö=yÅJ	Ü…&”|²ƒåîc´ã;A'× æ¬»¹ŠD@¥&P¥±’0x=:óÔÖ~Õ©$¾Í©N÷v½ÌÓÈAü½rG#ÿ Õš›p‘Àc¸ñ‘§Œc¹ÏÖ½oW]5ıO‚ãZßWÈñÒêá/È÷Ÿ…“¼fµ{”¹¶³¹i¨b?x¼cé^}ª¾¡w{8Œ[K,³|§-óe†ö';‰ëŸ¥}>«XhÃ›cñp>Ïšbùu«7¯Ìm¹cS(ß´ïÀáÏN§¾{ı}j.C32®<õbG±äı1_#¬¥'{ŸÓX4£wëızŒiÄÀnAùJã ÏÏ9ïô©DP#`Ì˜ù¹ûÇ¯^y5D¯uñ?óG³e+îõıArK2•WişEbp"àã©cíÜúÖ•¬‚Fb]#‰“8=s“ógœõ<
ç¨ïQ.ß×êv&¤•ş¡se=³K0†tßîÈn»9ãè{Öde±"²†-üXäuåsĞÒ‹å¨›Ñ3W($¬®Y·‰ğ—b>S‡$õ?ãK&U²Œc<¹}È­åy8·Ğæ¬ãy[[ÿ Á+ÄåŸ,yÁàu9÷äã¿¥f‡ƒ{!\ıÖ^ =·qÔ÷­pï÷ŞğÇÎã§xÔºÙ3ñmß—§N²áwÊ‚$dÇqäœzßøQ¦ßÍr.UÖIn$G–ÛJ8É<px?Ö¿]ÉÔ©åijÏóÆ<ÃÅ|>;¯kz_ˆ/î~ÛåÌàK	)0bY‹¯|¿xúÿ :Àk ï¹‰ }îíœ}‹õ¯ÏóIsV©.¬ÿ Lø°¼7•QJÜ´¡ÿ ¤’Ç*Ÿ3'FW	õî?Î}jhdG;”llŒœœ–'¯'ŸZùªßÄõæ}ìSºò©˜Š¶ãŒŒ‘Ó$™íÚ­ˆüØÈÀ'qèÙç8äóÓœúÖw×Ìë¥7e"ÅªÛ*yraœÈÍÂıH8Éæ¥İåÃ[[²‚±³+ e XğJ#yM[dSmÉIîÿ ¯ĞÊi2Ûd8U|7Bp,:g×òõ È	>[e±€O_Äc3Ít(Ê*ÿ Y·.İãsûşÇ<”Ï0`’¤•äƒéÏSúVçjK’Qæè …¤HÛæ\³(}¤3ƒsÏO­[á°QÜm|ü¬2{œî>üäÔ=eg²ÿ 3šQç¼—»Íÿ d§(ª­ÄÁ;vçßùõ?Ê•­¤’ğ°À˜ç '¨9É¡M¥Í¼wÿ ‚sVoŞ×úÔŠ#p­Á\t,zuçk+^f–îÙ!p&·Dy†ßŞ6I(8ù°=Çzı'€&«f´©s]´	}7g(p)­oÔúá>¤émäÅÅ:B]İòåvÛÂ“ÎsîkÍ¼F6«y,j7›Éˆ?!Cİºç¯ªñ‡±§A%ñ~§Â}åír\Æ¢zFëñ9ù‹d«¨^Ç§¿jØ ìÈÆ[¿#¾}ëñ†“ßSı ¥QÅ+î84nüŒ/Ì£<>ñäãœş~ô«<P”IaŒ^O cŒçÔŸåJ¤y[{¦t:Í§Ìõc<¨Y·Œ‡/ÇS‘_ğõ§Ü$h˜9RrrHÈ?çıkš3iKİêmJnWÓFQO—#=O ÷Áç§ñ÷©YJ7˜‹°å:è4œ¹c~¤2gáÆÓƒ‚:ààóèy<S¥7’H²$±»2¬{H#j´gÔŸğ¬ìı¥íîœu*èúù•gK‹g(í°rCu<vÿ =ª'Ü( ñÉ<nÏ<g=}AõªwrN:É_äyµê®]ÿ ¯êäM#E¥7	¶Š “èr3ŸÆ¤Ï<[™•T¨È äŸ\çûúŠë¥iS]¯øsçqUlŞ§3â¨$“EšŞ_—f$„– — ãÔ¶qÛÔÖ÷ÁûC¶×:¶ÙÖDURdzõ8Éç·ñ{WìÜ½
¤R²Lÿ $~—ô]n?Ëêòï8şl÷ï‰W/.“£;J¢Şæy[ÊeÚâ[UXóşŞ1ç_>^ì2n ²†ï€qÜAõç>µñü].lÆ«?Ğo£áÖKwöä5¤Ê«Ïÿ ¯ñè{{ÕˆäX"€‚	9Éç<ç“×“üëã’M)=Ş§ìòn)½Å1´ØfÀrO#ŒŒõç¦i–‘Á,Ä‚RynCàzäN{úúPêE;7«2sºåå÷Ÿõù‡”ìw±bŠÇ Œd××=ê£ûbb?• “œÄsÓÖ©4œ¹•ÑÏQ¤’RøÍî%“+J
œ–oâ'Éúÿ Zè4UÔ~ÓˆVX£*»—p;'§­wamíè¥Õ£òï_übyÅµN”şZ3€ø¥§†í,!’xíïe”\Å:r²FpT–üÊWwçU<{{so}!»K:/›8İûÄãå'#'ü­~íša]¥U­Z[Ÿå×‚µãWÅšŠ?óú_ƒ_ähN¹ˆ8eÁûßŸQÔsÖ¾lø¯ƒP†öYpc_&àÏ#œdøšü—ÿ y%Øÿ B¼S çÂu–ö³üÖxV6û."”òä‰K“–fùy>£œpOs^á¤¯Ù8YV0 n§®Ñœóéø{W­Uşí]÷üÏãú4äçÚÏõ;{[G$òbäM–Ú7?Nü­vğv¥ÈÚ@ùFq‚qêyÆWò¯"¤Ú“IÚÿ ğA´´6m{xÔ-Ãf3¹
¶6?c×ïgG­l[\jÚİÂ[-Ê¯—Í3È¡K¬cœ‘ÕÎG:’³×Oëò6åöwr¼¤Í4…6|Ç/¸rr;¶zcëëOw)p $çëıÏÖ®4lµÜrôŞæuã,æ% óÎ	$Œääñ‚{v÷¬kÉ#â$Thş^î-s»<g§¥oNœ[Ñÿ W9%ñËúêÎNòi.îoÌ’L¢ÈÛ¾Utg=‡Ò¸BÌòm üóÎ	üºşµİFé=.sbRq}Ï0×Œ¨²“'LA$ğr9şuæš‡ÎŒ²-““Ÿ©ı}k¾Ê-{·>[(ÚIny¶µ.Õ™T¨0²W<zqœr{WAšæ4HMÛñòç©'$ÿ Ÿ­z”g-ú³óLæŠue%Õº…z1‘»÷ôÈÈõ«[I,£ylçqçÛ’O¯ò®èMÙ¸ë©ãF›ÖúßúıÜèeÚ7nÃ ò¸ş~õ…4içË!.¢Êä  r^zqş5ÑJz¾ÏúıH©^úùŒÎ=¦5XÀ\ã#œŸrr2sùÕ¸,IW!JñÈãæöãµ*²Wæ_gÄæRn+«êR™SÌH™¶1}£9ù½3ø÷>şµbå&òoÁËÉÉ9aÛ9ëX)ÏG‰ƒV¶è†wŒÆå€m»dP3óœädğyÏ¹¨õ®ŸËò³++sÎòõëÁ÷ô®…®ì‰î¹Öæ½¹aç!y O§§<zúÕUŠY$’6BC’`Iç rŞã­	ÚjıN×\Í-Jw¶^C¢.^<eËò±#§?_¥VH.~y ,¤) €{ œúŸ­jæ’½îÎE›§ı}ã›jª5ÍÈÊKÌOëÇ'?ˆ«â’TŠWpÌ‡`ÇÊí€@b¹ïM5+É=¬’İ/{üØAi{æ´w/
GıÒ¤8ÉÉ;¸'9¯¶–åC*Åd©ÁÆp	äã§ô­æ•­sY-"şó2Yà’!'ÊÌùmİqI ç?¯Zô9`í‘¤@6–8%IëÆ0Iàş^õÇ^|É·­Nv¦Ü¶9¿[Ä÷l-œI‹FN
›¼y®0+,†V9 FqÁÏZtf”»›r{Dì®¿áËÊ¦1”;IsÜñÎO^şõzÏ;‰XîI`£W=01ÚºÕtú]œu)Ëšû²µ½–ÕicgS/n7Ï<ã××ÓÖ˜æxæËvê9íÏ=h”ùÓVÜ İí%tÍ(˜»Aù½sëÛ ãõõ§ (À>@È#ƒ×'œÒ²U¢›³ÜÒ*Rkİ²4>ÕbÜHà°‡|ó|cğ¦“Q¶@Hb;ç=yíì?;©Şò½ÍÕ¹I429M ¦$Ip@œ`£‘ÏÖ–$ûDrHc !98<©àç=éT—$l•ÊrvºW¹vÂâXe(Š º³À199éÜvüëLg{¹å å·l¸p3µTñÏ9ú×<j9_[êiN.)·ö¿à‘Oû¸ÒB»‹9Ğ{ıAëQÅ
³4êêy,“‘Ë|¾ÿ )üıë¢)A;+÷V¬“ÖL©tMÑÅ«©‘NŒ÷çüØê}*0²ÆÊ¨ß6>pyF<ä‘Û“šsŸ,y–¤6ÒßŞf}ÜW>j"«rwİù¿\†]¤@ÍFIãœzç†¥ßâvf”âÓmõ%¹‰ÔŒËÁûÇ œqŸ_Ö±Z	g.€FOŞèrIäqƒ×?‰§)Y^å8óI6ô,­™KG.Ùx(v“Œdwëé×ÓÖÖBÄ’°iYñ½O;‰63søšæw—3¾ÿ æÁ¨ÚVİf°UUŒcÌŞNHçğ>`=OCÜRİéoxÖêÄˆÀÃ‘‚§¤ÉÏ?L"Ö³•ØçOš7KOÔÌ›FX7å”ä(ÁÆy#®y?Ê²®ôYg@d‘çz‚Juç'ñ]jºJ÷ÜóçBW¿qğYÜÛÂ	Æ3´1ş0rrO'-‘Ç¸ô¨îlß#F#}ç.¤óÓ “Î:Œæ”gI¾kÈÆTçwËûŞ&‰Ç*q–éÎN=zóš»šeˆ‘óøs×éU-›¶©Ó…áw¯õÿ ¯äıŸ†¸Gb1Ç~õë%ËÈª¹dÀé=1“ÔçXÆ¤õ¹Ñìïõd"Ú[%uÎÓ($•aœãéÛ¯¥ušMÌsÃd±0w’sÔã$öëQ)j›z_×Ìå+ÚÛo´î;Á•$r d’zä7==­s—UÔw„Ä3óxÁëœO=ı=kZ:Ş÷9Úå”¹Ú+›9÷}T÷=º{ŞÕ§mbêŸ9ùGCé×9<ûrOzÚr|şì´fô¹œm»ş¿[”oäx1’przô=y'©<
Ãº¹Fœ¾O$ç#<Øõõ­èÊíÉ-YÏˆo£ş´*ËnªÈÌw™Iôô8Ï¨ÿ õÔ %ÁØwo19'8ëÛÓ5ëA'[CÉ©w(İ]¿ø…¤/o.ç…`A8ä¸ÿ õÖ‹Èò‚à Gã g®á¿bıÚ’]ÿ ¯ÔÚšrÓšåHíĞÊÓÊc Ü·<sŒõÄ˜HÛFqÇ'=‡ ?äÕÒ¿4¯¯ôˆ”-;ŞÌ¦–†‘ÁT÷Ï\çô¬ÙdÄ¸PBp?>}úwïí[·î·³`öåòê0£'œüH¥
‘¨,Á˜ão<Ç'Üç@©ü,—;™SœÇ×ùsúÖÚ#˜ğ ©ó0<·~IõqíS5x¾èµÍ-R'‡ÏÂ“¼FÁsŒõàç'¿¿­vZ~£öeUŠGW8ù†.O©=qı+›W5«ÌÛÓCµ°.Îç–Ác“Õ<“ëíıkÒô›­¡/p¡Ö@æÆGÊA$‘ÎN	şuÅQ¸YŞÈÒÛ³~ó;ßÚÁs|4ùtö¸Y•9H>’@Á<ãùW¥ËğÚÕí’[3šVaÈonORİ…8Tnw¾ßğN•†»Zjyõïƒ5-6;˜­nÁÃ¡ÎFsÀ$zàõ?Ö¼êI|KáÉÌOs%N8%£89;IÁ>‡Ú½Ü#v×ŞFœ®]kî‰sDÓÍ=¡ıÔs³´JGP ;H$r;×¢[şÓ:|óCq®ZÜNë"½ÌQ6Ò	\"€ÏŒu>µëS­NÜ²êsK(tëı~gymûGx"ö	cµşÓ²i•€Š]§íËn9n'ß¯­c?Ä
_¯=Ü+å†daIÂwq“J­*5²»Ü_YšÔ§â}ì‚Hå[¤™í#që´“–À'?¥eKy!°IZ"di<ª]Œ‚9Ïø×ˆÁAÊÉ]_ävSÄ]k³9›UO*æIr–ò‡LíÈÜÙü¼ 3É¬¸uôÍâŞ+wÏ±€xäŸPOë\U0\±Ñ^F‰ı“36ÒÇzñlUœ;Èˆª¸v\˜^0IıkÌYÆ¦¢|‚åÏ ¼½ë’®pƒÓVRÇ&Õ¥d[ŠÒÊb<ÛˆÔÃÈ?İç w=ë
}-MÜ…0ñnàÔ¶{wÍpG.kµ¿ùšsª±æş¿­È^ÎÆÕ‹H™FfE¾9Îr{ÿ Zå®¢†çRK+–FC4¡¶îá‹’!AÈÉ®ºt]›z4eRJ3~õ×õÿ K³ÍË‡el9CÃc9õÏ__çNšÒŞh
##æİ®q{Ïõ¦Ô¯~[ÿ ^„J²ÓŞµŠ²Yù™ 1’Jñ¼ƒÔ÷ÁÎô¤´ÓãóK›‡NT… ‡ù²G^ç?¥Dá'nm,iN¥äù¥uıÁ}h¾c}”ª±ûäùë’zŸ¯¯¥Mib±5ß‘ÏóÏ¨ÿ õ×'³æwŞß×èi:Š*÷» ¼.Ô¤©°àî9äã öÇçTÌVíoƒ¼Ä'«ÆHàã’GãV°òrï~ç=JªM+ëÿ c;ÄÂT.rÌIêsÇÊ„hÃ#Îcqè~Ã•8ü¥uFíîìaRm'©Õäp(X]$`sŸLŒúç½MS“VšRR›öà…8û»‡#ƒóúšèXVÕÿ ¯ëær{i¾kj¿¯1³ÖÂåÆA@õç99'üŠÊşÒi\™YQ·áp1òäã¡çêOzÚ4Zô5^dÓÕ™e\ˆÜÇ#¡ïøÔRM(AIûµ+ØàprsÏåNpPo­Í!4ïîÚÅX–GfRÀã'¨ëœúò8şUViT»)%X`sÉúûàŠ«ò»òÜ©G1èÙ²É˜ğÁëÏ<ÿ ŸZy`’ƒóŒd§8ç¡§)¶ôĞg¯¼ùˆ¤“¢üÌ‡®NIõÏÔsëïQ7”\…ù@<ÇŸSy>µİ½[6ŒšNËWÿ •'Ø»0ê~£=ÏrzûÔFæI•†0W'>§÷<sTk>gÕ¡ŠÅYdˆ€O g×§Lvª÷WX“ğ¹äc ‚^¹§”¥}ßüŠÄ·©$9d6œÜğÜg¿'9§DÌ]÷2í	Ïn}x=jêKİÑë"^hOZÉ¬Šå²!p3×‚IÎò5Rá¤Û¶=ÄgŒöÇesñ¬cw&œ¾/ó´³İ g†á±ÄóÓ~¹ç÷®†5På‘Õ³ƒ’r	¹=yçÖ©ÓpWNé	½SZ•îÚRÅ‰²qøß˜8'½WµGšCœn$dğ,?Ã½$î“îu]5êQ·]ˆòVî}NTÈ]Ù`ŞÁ²¢6ë–=Ú¸û(ŸQšâBVÊ+iğ!ÀùÔ7>XËùšä„õRJéŸ¬Uƒ“½®m IÜ3²€şøğONrx>¾µÕXÇsiZ•¡†úæHÎû)SrÄ¥
‘ 8	,1ì}kªwzªñĞ®Ñ