
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrontPage.java
 *
 * Created on Jul 27, 2012, 8:32:22 AM
 */

/**
 *
 * @author xiia1-10
 */
public class Password extends javax.swing.JFrame {

    /** Creates new form FrontPage */
    public Password() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, -10, 250, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 190, 115, 29);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setForeground(new java.awt.Color(51, 102, 0));
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 380, 130, 50);

        jList1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 180, 70, 250);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18));
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(500, 190, 160, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("create new account");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(670, 430, 180, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel5.setForeground(new java.awt.Color(204, 153, 255));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 0, 0);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Delete account");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 460, 137, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 518);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if (jPasswordField1.getText().isEmpty())
    {
    JOptionPane.showMessageDialog(null, " plz enter your password");
     }
    else
     {
     {
    if (jPasswordField1.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null,"plz enter some value");
        }
        String password=jPasswordField1.getText();
        String a="user_id";
        String b=(String) jList1.getSelectedValue();
        String c=password;
      
        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/g_shop","root","");
            Statement stmt=(Statement) con.createStatement();
            String query="select * from password where user_id='"+b+"' ";
         ResultSet ak=   stmt.executeQuery (query);
        if(ak.next())
        {
         if(c.equals(ak.getString("password")))
        {
        JOptionPane.showMessageDialog(this, "login successful");
        new FrontPage().setVisible(true);
        this.dispose();
        }
        else
        {
             JOptionPane.showMessageDialog(null,"password wrong");
        }
        }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
       
        jPasswordField1.setText("");
      
         
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
new signup().setVisible(true);    
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
     if (jPasswordField1.getText().isEmpty())
    {
    JOptionPane.showMessageDialog(null, " plz enter your password");
     }
    else
     {
     {
    if (jPasswordField1.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null,"plz enter some value");
        }
        String password=jPasswordField1.getText();
        String a="user_id";
        String b=(String) jList1.getSelectedValue();
        String c=password;

        try
        {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/g_shop","root","");
            Statement stmt=(Statement) con.createStatement();
            String query="select * from password where user_id='"+b+"' ";
         ResultSet ak=   stmt.executeQuery (query);
        if(ak.next())
        {
         if(c.equals(ak.getString("password")))
        {
        JOptionPane.showMessageDialog(this, "deleted");
        String q="delete from password where user_id='"+b+"' ";
      stmt.executeUpdate(q);
        }
        else
        {
             JOptionPane.showMessageDialog(null,"password wrong");
        }
        }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }

        jPasswordField1.setText("");


        }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultListModel d1=(DefaultListModel)jList1.getModel();
           d1.removeAllElements();
        try {
            Class.forName("java.sql.DriverManager");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/g_shop","root","");
            Statement stmt=(Statement) con.createStatement();
            String q="Select * from password;";
            ResultSet rs=(ResultSet)stmt.executeQuery(q);
            while(rs.next())
            {
                d1.addElement(rs.getString("user_id"));

            }
            jList1.setModel(d1);
        }

        catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
           jList1.setSelectedIndex(0);

    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
